version: '3'
services: 

  mlflow:
    build: ./mlflow
    volumes: 
      - ./mlflow/db:/mlflow/db
      - ./mlflow/artifacts:/mlflow/artifacts
    ports: 
      - "5555:5555"

  jupyter-lab:
    build: ./jupyter-lab
    volumes: 
        - ./project:/project
    ports: 
        - "8888:8888"
